/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(freq_step_controller.h)                                    */
/* BINDTOOL_HEADER_FILE_HASH(placeholder_hash_value)                               */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/freq_step_controller.h>
#ifndef D
#define D(...) ""
#endif


void bind_freq_step_controller(py::module& m)
{
    using freq_step_controller = ::gr::plasma::freq_step_controller;

    py::class_<freq_step_controller, gr::block, gr::basic_block, std::shared_ptr<freq_step_controller>>(m, "freq_step_controller", D(freq_step_controller))
        .def(py::init(&freq_step_controller::make),
             py::arg("start_freq"),
             py::arg("stop_freq"),
             py::arg("step_freq"),
             py::arg("loop"),
             D(freq_step_controller, make))
        .def("init_meta_dict",
             &freq_step_controller::init_meta_dict,
             py::arg("tx_freq_key"),
             D(freq_step_controller, init_meta_dict));
}