/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ifft_range_profile.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6db57500ee4f45f1a88407e128e82289)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <QWidget>
#include <Python.h>
#include <gnuradio/plasma/ifft_range_profile.h>
// pydoc.h is automatically generated in the build directory
// #include <ifft_range_profile_pydoc.h>

// Fallback if pydoc header wasn't generated during build
#ifndef D
#define D(...) ""
#endif

void bind_ifft_range_profile(py::module& m)
{

    using ifft_range_profile    = ::gr::plasma::ifft_range_profile;


    py::class_<ifft_range_profile, gr::block, gr::basic_block,
        std::shared_ptr<ifft_range_profile>>(m, "ifft_range_profile", D(ifft_range_profile))

        .def(py::init(&ifft_range_profile::make),
           py::arg("bandwidth"),
           py::arg("pulse_width"),
           py::arg("sample_rate"),
           py::arg("prf"),
           py::arg("sweep_start"),
           py::arg("sweep_stop"),
           py::arg("sweep_step"),
           py::arg("freq_key"),
           py::arg("n_fft_synthesis") = 256,
           py::arg("parent") = nullptr,
           D(ifft_range_profile,make)
        )
        




        
        .def("exec_",&ifft_range_profile::exec_,       
            D(ifft_range_profile,exec_)
        )


        
        .def(
            "qwidget",
            [](ifft_range_profile& self) {
                return reinterpret_cast<uintptr_t>(self.qwidget());
            },
            D(ifft_range_profile, qwidget))

        
        .def(
            "pyqwidget",
            [](std::shared_ptr<ifft_range_profile> p) {
                return PyLong_AsLongLong(p->pyqwidget());
            },
            D(ifft_range_profile, pyqwidget))


        
        .def("set_dynamic_range",&ifft_range_profile::set_dynamic_range,       
            py::arg("arg0"),
            D(ifft_range_profile,set_dynamic_range)
        )


        
        .def("set_msg_queue_depth",&ifft_range_profile::set_msg_queue_depth,       
            py::arg("depth"),
            D(ifft_range_profile,set_msg_queue_depth)
        )


        
        .def("set_backend",&ifft_range_profile::set_backend,       
            py::arg("arg0"),
            D(ifft_range_profile,set_backend)
        )

        ;




}








