/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sweep_collector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2b62c4a5dd6d9f587504c6d4b8fc7158)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/sweep_collector.h>
// pydoc.h is automatically generated in the build directory
// #include <sweep_collector_pydoc.h>

// Fallback for missing pydoc headers
#ifndef D
#define D(...) ""
#endif

void bind_sweep_collector(py::module& m)
{

    using sweep_collector    = ::gr::plasma::sweep_collector;


    py::class_<sweep_collector, gr::block, gr::basic_block,
        std::shared_ptr<sweep_collector>>(m, "sweep_collector", D(sweep_collector))

        .def(py::init(&sweep_collector::make),
           py::arg("output_prefix") = "sweep",
           py::arg("output_dir") = ".",
           py::arg("save_cycles") = 1,
           py::arg("sweep_start") = 0.,
           py::arg("sweep_stop") = 0.,
           py::arg("sweep_step") = 0.,
           py::arg("freq_key") = "rx_freq",
           D(sweep_collector,make)
        )
        




        
        .def("set_sweep_params",&sweep_collector::set_sweep_params,       
            py::arg("start"),
            py::arg("stop"),
            py::arg("step"),
            D(sweep_collector,set_sweep_params)
        )


        
        .def("set_freq_meta_key",&sweep_collector::set_freq_meta_key,       
            py::arg("key"),
            D(sweep_collector,set_freq_meta_key)
        )


        
        .def("set_output_prefix",&sweep_collector::set_output_prefix,       
            py::arg("prefix"),
            D(sweep_collector,set_output_prefix)
        )

        ;




}








