/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(usrp_radar.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b727d2e9f61c84ba7d07b329aea53ae7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/usrp_radar.h>
// pydoc.h is automatically generated in the build directory
#include <usrp_radar_pydoc.h>

void bind_usrp_radar(py::module& m)
{

    using usrp_radar    = ::gr::plasma::usrp_radar;


    py::class_<usrp_radar, gr::block, gr::basic_block,
        std::shared_ptr<usrp_radar>>(m, "usrp_radar", D(usrp_radar))

        .def(py::init(&usrp_radar::make),
           py::arg("args"),
           py::arg("tx_rate"),
           py::arg("rx_rate"),
           py::arg("tx_freq"),
           py::arg("rx_freq"),
           py::arg("tx_gain"),
           py::arg("rx_gain"),
           py::arg("start_delay"),
           py::arg("elevate_priority"),
           py::arg("cal_file"),
           py::arg("verbose"),
           py::arg("hop_start_freq"),
           py::arg("hop_end_freq"),
           py::arg("hop_step"),
           py::arg("lo_stabilize_time"),
           py::arg("step_delay") = 0.050000000000000003,
           D(usrp_radar,make)
        )
        




        
        .def("set_metadata_keys",&usrp_radar::set_metadata_keys,       
            py::arg("tx_freq_key"),
            py::arg("rx_freq_key"),
            py::arg("sample_start_key"),
            D(usrp_radar,set_metadata_keys)
        )

        ;




}








